.TH endless\-sky\-editor 6 "14 May 2015" "ver. 0.7.10" "Endless Sky Editor"

.SH NAME
endless\-sky\-editor \- universe editor for the game Endless Sky.

.SH SYNOPSIS
\fBendless\-sky\-editor\fR [\-h] [\-\-help] [\-v] [\-\-version] [\fImap file\fR]

.SH DESCRIPTION
\fBEndless Sky\fR is a space exploration and combat game combining action and role playing elements. This program is used to edit the "map.txt" file, which defines the locations of star systems, the links between them, the stars and planets within each system, and various attributes of each of those objects.

The game's images will be loaded from ../images, relative to the location of the map file that you load. That means that before a map file has been loaded, no images are available.

For more information, visit https://endless\-sky.github.io

.SH OPTIONS
.IP \fB\-h,\ \-\-help
prints a short help message.

.IP \fB\-v,\ \-\-version
prints the software version.

.SH AUTHOR
Michael Zahniser (mzahniser@gmail.com)

This is free software; you can redistribute it and/or modify it under the terms of the GPL.
