name: CI

on:
  push:
    branches: [ master, actions ] # TODO
  pull_request:
    branches: [ master, actions ] # TODO

defaults:
  run:
    shell: bash

jobs:
  build:
  
    strategy:
      matrix:
        target:
          - linux
          - windows
          - macos
        include:
          - target: linux
            os: ubuntu-latest
            artifact: endless-sky-editor
          - target: windows
            os: windows-latest
            artifact: endless-sky-editor.exe
          - target: macos
            os: macos-latest
            artifact: endless-sky-editor

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/Qt/
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.15.2"
        dir: ${{ github.workspace }}/Qt/
        arch: win64_mingw81 # This is only used (and needed on windows, so we can safely specify it for all OSes
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        
    - name: Run qmake
      run: qmake
      
    - name: Run make
      run: make -j $(nproc)
      
    - run: |
        git status
        ls -la
        ls -la release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: ${{ matrix.artifact }}
        
    
    
    
    
