name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  build:
  
    strategy:
      matrix:
        target:
          - linux
          - windows
          - macos
        include:
          - target: ubuntu-latest
            artifact: endless-sky-editor
            binary: endless-sky-editor
          - target: ubuntu-18.04
            artifact: endless-sky-editor
            binary: endless-sky-editor
          - target: windows-latest
            artifact: release/endless-sky-editor.exe
            binary: release/endless-sky-editor.exe
          - target: macos-latest
            artifact: endless-sky-editor.app/
            binary: endless-sky-editor.app/Contents/MacOS/endless-sky-editor

    runs-on: ${{ matrix.target }}

    steps:

    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/Qt/
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.15.2"
        dir: ${{ github.workspace }}/Qt/
        arch: win64_mingw81 # This is only used (and needed) on windows, so we can safely specify it for all OSes
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Run qmake
      run: qmake

    - name: Run make
      run: make -j $(nproc)

    - name: Run --version
      run: ./${{ matrix.binary }} --version

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: ${{ matrix.artifact }}
