name: CI

on:
  push:
    branches: [ master, actions ] # TODO
  pull_request:
    branches: [ master, actions ] # TODO

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: '${{ github.workspace }}/Qt/'
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.15.2"
        dir: '${{ github.workspace }}/Qt/'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        
    - name: Run qmake
      run: qmake
      
    - name: Run make
      run: make -j $(nproc)
    
    
    
    
